"""Report generation helper."""

from __future__ import annotations

from pathlib import Path

from .metrics import MetricsReport


def render_report_stub(metrics: MetricsReport) -> str:
    """Render the lab report from observed metrics."""
    row_template = (
        "| {scenario_id} | {expected_route} | {actual_route} | "
        "{success} | {retry_count} | {interrupt_count} |"
    )
    rows = "\n".join(
        row_template.format(
            scenario_id=item.scenario_id,
            expected_route=item.expected_route,
            actual_route=item.actual_route or "",
            success="yes" if item.success else "no",
            retry_count=item.retry_count,
            interrupt_count=item.interrupt_count,
        )
        for item in metrics.scenario_metrics
    )
    failed = [item for item in metrics.scenario_metrics if not item.success]
    failure_summary = (
        "All sample scenarios met their expected route and produced a user-facing result."
        if not failed
        else "Scenarios needing review: " + ", ".join(item.scenario_id for item in failed)
    )
    return f"""# Day 08 Lab Report

## 1. Team / student

- Name: Student
- Repo/commit: local workspace
- Date: generated by `agent-lab run-scenarios`

## 2. Architecture

The workflow is a typed LangGraph support-ticket agent:

`START -> intake -> classify -> conditional route -> finalize -> END`

The conditional branches are:

- `simple`: answer directly for safe knowledge requests.
- `tool`: call the mock support lookup, evaluate the result, then answer.
- `missing_info`: ask a clarification question instead of guessing.
- `risky`: stage the action, require approval, then call the tool.
- `error`: enter the bounded retry path before tool execution.

Every branch terminates through `finalize`, and retry routing is guarded by
`attempt < max_attempts` so transient failures cannot loop forever.

## 3. State schema

| Field | Reducer | Why |
|---|---|---|
| `route`, `risk_level` | overwrite | current route and risk class |
| `classification_reason` | overwrite | explanation of the latest route |
| `attempt`, `max_attempts` | overwrite | bounded retry control |
| `final_answer`, `pending_question` | overwrite | latest user-facing outcome |
| `approval` | overwrite | latest HITL state |
| `messages`, `tool_results` | append | conversation and tool audit trail |
| `errors`, `events` | append | metrics and recovery inspection |
| `thread_id` | overwrite | stable key for checkpointer history per scenario |

## 4. Scenario results

| Scenario | Expected route | Actual route | Success | Retries | Interrupts |
|---|---|---|---:|---:|---:|
{rows}

## 5. Metrics summary

- Total scenarios: {metrics.total_scenarios}
- Success rate: {metrics.success_rate:.2%}
- Average nodes visited: {metrics.avg_nodes_visited:.2f}
- Total retries: {metrics.total_retries}
- Total interrupts: {metrics.total_interrupts}
- Resume / state-history evidence observed: {metrics.resume_success}

## 6. Failure analysis

Retry or tool failure: error scenarios produce `ERROR:` tool results until the
retry count reaches the configured limit. The `evaluate` node marks these as
`needs_retry`; `retry` increments the attempt counter; `route_after_retry`
sends exhausted runs to `dead_letter`.

Risky action without approval: risky keywords route to `risky_action`, then
`approval`. If approval is rejected, routing moves to `clarify` rather than
executing the tool path.

Observed sample outcome: {failure_summary}

## 7. Persistence / recovery evidence

Each scenario uses a deterministic `thread_id` and compiles the graph with a
checkpointer. The CLI calls `get_state_history()` after invocation and records
`resume_success=true` when checkpoint history is available.

SQLite support is implemented in `persistence.py` with an explicit connection,
WAL mode, and `SqliteSaver(conn=...)`, so the same graph can be run with durable
checkpoints by setting `checkpointer: sqlite`.

## 8. Extension work

Bonus extension: Streamlit UI. `langgraph_agent_lab.ui` provides a demo
interface for scenario selection, custom tickets, two-step HITL review,
approval/rejection, retries, tool results, and the audit timeline.

Additional extensions:

- Graph diagram export: `export-graph` writes `docs/graph.mmd`.
- Time-travel evidence: `demo-history` writes checkpoint snapshots to
  `outputs/state_history.json`.
- Crash recovery evidence: `demo-crash-recovery` rebuilds the graph/checkpointer
  against SQLite and writes `outputs/crash_recovery.json`.
- SQLite checkpointer support is implemented for durable recovery demos.
- Graph/checkpoint evidence is included in the generated metrics and this report.

## 9. Improvement plan

With another production pass, the first upgrades would be replacing keyword
routing with a policy-tested classifier, storing dead-letter items in a durable
queue, and adding real authenticated reviewer identities for HITL decisions.
"""


def write_report(metrics: MetricsReport, output_path: str | Path) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report_stub(metrics), encoding="utf-8")
